name: CI/CD for R

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Check R version
      run: |
        R --version

    - name: Install dependencies
      run: |
        install.packages(c("rmarkdown", "knitr"))

    - name: Run R script
      run: |
        Rscript -e 'print("Hello, world!")'
